USE heroku_c6a7cf1db3cfbbc;
DROP TABLE IF EXISTS PETITION_LIST;

CREATE TABLE PETITION_LIST(
    PETITION_ID VARCHAR(20) NOT NULL,
    PLATFORM VARCHAR(40) NOT NULL,
    CATEGORY VARCHAR(40) NOT NULL,
    TITLE VARCHAR(120) NOT NULL,
    CONTENT TEXT,
    AGREEMENT_COUNT INT DEFAULT 0,
    WRITER VARCHAR(45) NOT NULL,
    WDATE DATETIME,
    PRIMARY KEY (PETITION_ID)
);